# Controller configuration with multiple workers
video:
  source: 0
  log_level: INFO
  profile_window: 1.0  # Show max task time over last second

detector:
  model: yolov5nu.pt
  frame_skip: 50
  log_level: INFO
  profile_window: 5.0  # Show max task time over last 5 seconds
  events:
    - video: frame  # Receive frame events from video

navigator:
  target_class: 0  # Track humans (class ID 0)
  log_level: INFO
  profile_window: 1.0
  events:
    - detector: detection  # Receive detection events from detector

ui:
  log_level: INFO
  profile_window: 1.0  # Show max task time over last second
  events:
    - video: frame        # Receive frame events from video
    - detector: detection  # Receive detection events from detector
    - video: worker_profile      # Receive profiling data from video worker
    - detector: worker_profile   # Receive profiling data from detector worker
    - navigator: worker_profile  # Receive profiling data from navigator worker
    - ui: worker_profile        # Receive profiling data from UI worker
