# Controller configuration with multiple workers
controller:
  log_level: INFO # Log level for the controller itself
  log_file: "/tmp/vanishcap.log" # Optional: Path to log file
  offline: false # Whether to run in offline mode (no WiFi management)
  wifi:
    connect:
      ssid: "t2" # Optional: SSID to connect to before starting workers
      password: "" # Optional: Password for the SSID
    reconnect: true # Optional: Whether to reconnect to previous SSID after workers finish

video:
  source: "udp://@0.0.0.0:11111" # Tello video stream
  save_path: "/tmp/vanishcap_recording.mp4" # Path to save the video
  log_level: INFO # Show frame acquisition info
  profile_window: 1.0 # Show max task time over last second
  depends_on: ["detector", "drone"] # Wait for detector and drone to start

detector:
  model: yolov5nu # Base model path without extension
  backend: tensorrt # Use ONNX for cross-platform compatibility
  frame_skip: 1 # Process every frame
  log_level: INFO # Show frame processing info
  profile_window: 2.0 # Show max task time over last 2 seconds
  depends_on: [] # No dependencies
  events:
    - video: frame # Receive frame events from video

navigator:
  target_class: "person" # Track people (class name)
  log_level: INFO
  profile_window: 1.5 # Show max task time over last 1.5 seconds
  depends_on: ["detector"] # Wait for detector to start
  events:
    - detector: detection # Receive detection events from detector

drone:
  offline: false # Whether to run in offline mode (no WiFi management)
  ip: "192.168.10.1" # Default Tello IP address
  max_linear_velocity: 80 # Maximum linear velocity in cm/s
  max_angular_velocity: 120 # Maximum angular velocity in deg/s
  follow_distance: 100 # Distance to maintain from target in cm
  follow_target_width: 0.3 # Width of target to maintain in proportion of frame width
  follow_target_height: 0.85 # Where on the target's height to center (default: 0.85)
  movement_threshold: 0.1 # In normalized coordinates [-1, 1]
  field_of_view: 86.2 # Width of camera field of view in degrees for time-based yaw control
  delay_between_timed_yaws: 1.0 # Delay between timed yaws in seconds
  percent_angle_to_command: 100 # Percentage of target angle to rotate in each yaw command [0, 100]
  auto_takeoff: true # Whether to take off automatically without waiting for a target
  disable_yaw: false # Whether to disable yaw rotation
  disable_xy: false # Whether to disable forward/backward and left/right movement
  disable_z: false # Whether to disable up/down movement
  log_level: DEBUG
  profile_window: 1.0 # Show max task time over last second
  depends_on: ["navigator"] # Wait for navigator to start
  events:
    - navigator: target # Receive target events from navigator

ui:
  log_level: INFO # Show frame display info
  profile_window: 1.0 # Show max task time over last second
  depends_on: [] # No dependencies, can start anytime
  events:
    - video: frame # Receive frame events from video
    - detector: detection # Receive detection events from detector
    - video: worker_profile # Receive profiling data from video worker
    - detector: worker_profile # Receive profiling data from detector worker
    - navigator: worker_profile # Receive profiling data from navigator worker
    - ui: worker_profile # Receive profiling data from UI worker
